// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/audio_streaming.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AudioChunk struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	SampleRate           int32    `protobuf:"varint,2,opt,name=sample_rate,json=sampleRate" json:"sample_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioChunk) Reset()         { *m = AudioChunk{} }
func (m *AudioChunk) String() string { return proto.CompactTextString(m) }
func (*AudioChunk) ProtoMessage()    {}
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_audio_streaming_0e99a9ac0c31eff1, []int{0}
}
func (m *AudioChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioChunk.Unmarshal(m, b)
}
func (m *AudioChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioChunk.Marshal(b, m, deterministic)
}
func (dst *AudioChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioChunk.Merge(dst, src)
}
func (m *AudioChunk) XXX_Size() int {
	return xxx_messageInfo_AudioChunk.Size(m)
}
func (m *AudioChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioChunk.DiscardUnknown(m)
}

var xxx_messageInfo_AudioChunk proto.InternalMessageInfo

func (m *AudioChunk) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AudioChunk) GetSampleRate() int32 {
	if m != nil {
		return m.SampleRate
	}
	return 0
}

type RecognitionResult struct {
	Result               string   `protobuf:"bytes,1,opt,name=result" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RecognitionResult) Reset()         { *m = RecognitionResult{} }
func (m *RecognitionResult) String() string { return proto.CompactTextString(m) }
func (*RecognitionResult) ProtoMessage()    {}
func (*RecognitionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_audio_streaming_0e99a9ac0c31eff1, []int{1}
}
func (m *RecognitionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecognitionResult.Unmarshal(m, b)
}
func (m *RecognitionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecognitionResult.Marshal(b, m, deterministic)
}
func (dst *RecognitionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecognitionResult.Merge(dst, src)
}
func (m *RecognitionResult) XXX_Size() int {
	return xxx_messageInfo_RecognitionResult.Size(m)
}
func (m *RecognitionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_RecognitionResult.DiscardUnknown(m)
}

var xxx_messageInfo_RecognitionResult proto.InternalMessageInfo

func (m *RecognitionResult) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*AudioChunk)(nil), "proto.AudioChunk")
	proto.RegisterType((*RecognitionResult)(nil), "proto.RecognitionResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AudioStreamService service

type AudioStreamServiceClient interface {
	StreamAudio(ctx context.Context, opts ...grpc.CallOption) (AudioStreamService_StreamAudioClient, error)
}

type audioStreamServiceClient struct {
	cc *grpc.ClientConn
}

func NewAudioStreamServiceClient(cc *grpc.ClientConn) AudioStreamServiceClient {
	return &audioStreamServiceClient{cc}
}

func (c *audioStreamServiceClient) StreamAudio(ctx context.Context, opts ...grpc.CallOption) (AudioStreamService_StreamAudioClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_AudioStreamService_serviceDesc.Streams[0], c.cc, "/proto.AudioStreamService/StreamAudio", opts...)
	if err != nil {
		return nil, err
	}
	x := &audioStreamServiceStreamAudioClient{stream}
	return x, nil
}

type AudioStreamService_StreamAudioClient interface {
	Send(*AudioChunk) error
	CloseAndRecv() (*RecognitionResult, error)
	grpc.ClientStream
}

type audioStreamServiceStreamAudioClient struct {
	grpc.ClientStream
}

func (x *audioStreamServiceStreamAudioClient) Send(m *AudioChunk) error {
	return x.ClientStream.SendMsg(m)
}

func (x *audioStreamServiceStreamAudioClient) CloseAndRecv() (*RecognitionResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(RecognitionResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for AudioStreamService service

type AudioStreamServiceServer interface {
	StreamAudio(AudioStreamService_StreamAudioServer) error
}

func RegisterAudioStreamServiceServer(s *grpc.Server, srv AudioStreamServiceServer) {
	s.RegisterService(&_AudioStreamService_serviceDesc, srv)
}

func _AudioStreamService_StreamAudio_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AudioStreamServiceServer).StreamAudio(&audioStreamServiceStreamAudioServer{stream})
}

type AudioStreamService_StreamAudioServer interface {
	SendAndClose(*RecognitionResult) error
	Recv() (*AudioChunk, error)
	grpc.ServerStream
}

type audioStreamServiceStreamAudioServer struct {
	grpc.ServerStream
}

func (x *audioStreamServiceStreamAudioServer) SendAndClose(m *RecognitionResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *audioStreamServiceStreamAudioServer) Recv() (*AudioChunk, error) {
	m := new(AudioChunk)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AudioStreamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.AudioStreamService",
	HandlerType: (*AudioStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAudio",
			Handler:       _AudioStreamService_StreamAudio_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/audio_streaming.proto",
}

func init() {
	proto.RegisterFile("proto/audio_streaming.proto", fileDescriptor_audio_streaming_0e99a9ac0c31eff1)
}

var fileDescriptor_audio_streaming_0e99a9ac0c31eff1 = []byte{
	// 188 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8e, 0xc1, 0xaa, 0x83, 0x30,
	0x10, 0x45, 0xc9, 0xe3, 0x29, 0xbc, 0xf1, 0x6d, 0x9c, 0x45, 0x91, 0x76, 0x51, 0x71, 0x25, 0x14,
	0x2c, 0xb4, 0xdb, 0x6e, 0xa4, 0x7f, 0x10, 0x3f, 0x40, 0x52, 0x1d, 0x6c, 0xa8, 0x26, 0x12, 0x63,
	0xbf, 0xbf, 0x74, 0x14, 0xba, 0xe8, 0x2a, 0x37, 0xe7, 0xc2, 0xdc, 0x03, 0xbb, 0xd1, 0x59, 0x6f,
	0x8f, 0x6a, 0x6e, 0xb5, 0xad, 0x27, 0xef, 0x48, 0x0d, 0xda, 0x74, 0x05, 0x53, 0x0c, 0xf8, 0xc9,
	0x4a, 0x80, 0xf2, 0xdd, 0x5f, 0xef, 0xb3, 0x79, 0x20, 0xc2, 0x6f, 0xab, 0xbc, 0x4a, 0x44, 0x2a,
	0xf2, 0x7f, 0xc9, 0x19, 0xf7, 0x10, 0x4d, 0x6a, 0x18, 0x7b, 0xaa, 0x9d, 0xf2, 0x94, 0xfc, 0xa4,
	0x22, 0x0f, 0x24, 0x2c, 0x48, 0x2a, 0x4f, 0xd9, 0x01, 0x62, 0x49, 0x8d, 0xed, 0x8c, 0xf6, 0xda,
	0x1a, 0x49, 0xd3, 0xdc, 0x7b, 0xdc, 0x40, 0xe8, 0x38, 0xf1, 0xad, 0x3f, 0xb9, 0xfe, 0x4e, 0x12,
	0x90, 0xf7, 0x2a, 0xd6, 0xa9, 0xc8, 0x3d, 0x75, 0x43, 0x78, 0x81, 0x68, 0x01, 0xdc, 0x61, 0xbc,
	0x38, 0x16, 0x1f, 0xb3, 0x6d, 0xb2, 0xa2, 0xaf, 0xa5, 0x5c, 0xdc, 0x42, 0xae, 0xce, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb2, 0xdd, 0x16, 0x1b, 0xf0, 0x00, 0x00, 0x00,
}
